### PR TITLE
Overall course review

### PR DESCRIPTION
**Pull request by hectorsector**
As I'm going through the course, I'll commit changes directly. I'll toggle this out of draft when it's ready for review.

### CODE REVIEW

**Comment by hectorsector** [comment]
This is ready for review!

**Comment by hectorsector** [comment]
Friendly ping on this, @mattdavis0351. Waiting for review.

**Review by mattdavis0351 — APPROVED** [review]

**Comment by mattdavis0351** [comment]
@hectorsector Thank you so much for doing this.  You addressed quite a few of the notes that I have been taking while working through this with @brianamarie.

**Comment by hectorsector** [comment]
Thanks, @mattdavis0351 just added a couple of small commits to fix something that wasn't working. Shipping and opening a new PR for the error handling.

**Pull request merged**
