### PR TITLE
Prep the course

### PR DESCRIPTION
**Pull request by hectorsector**
This PR preps the course for release.

### CODE REVIEW

**Comment by hectorsector** [comment]
This is ready for one final review and can then be merged and the course can be toggled to public (even if I'm not around). /cc @mattdavis0351 @a-a-ron @lmkeston @brianamarie

**Review by lmkeston — COMMENTED** [review]
This is **very** nit-picky, but on step 2 you're instructed to change the name property on line 1, but depending on how that file is created, the name property is on a different line.  Just a tiny minor issue, feel free to ignore it...

**Comment by mattdavis0351** [comment]
@lmkeston do you know which response file that is off the top of your head?

**Comment by lmkeston** [comment]
> 
> 
> @lmkeston do you know which response file that is off the top of your head?

here you go @mattdavis0351 
image

**Comment by hectorsector** [comment]
> but on step 2 you're instructed to change the name property on line 1

I noticed this too. The template contains comments, and we remove those comments later which impact the line numbers. I took care of this in ec78ff1.

**Comment by hectorsector** [comment]
Merging this PR and finishing up the validation work in #6

**Pull request merged**
